### PR TITLE
Update code examples to use "!" syntax

### PR DESCRIPTION
**Pull request by a-lavis**
According to the [tutorial](https://www.roc-lang.org/tutorial#tasks):

> If you like, you can always call `Task.await` directly instead of using `!` (since `!` is nothing more than syntax sugar for `Task.await`), but it's a stylistic convention in the Roc ecosystem to use `!` instead.

so I thought I'd go ahead and replace usage of `Task.await` with `!` in the examples where it seemed simple to do so.  I hope this is helpful!

### CODE REVIEW

**Comment by Anton-4** [comment]
I believe tests are failing because of https://github.com/roc-lang/roc/issues/6765, we can revisit this PR when that issue is fixed.

**Comment by lukewilliamboswell** [comment]
The unwrapping in a pipeline was fixed by Kiryl. It's just a parsing bug now for multi line things. We should be able to modify the tests so they don't hit the parsing bug.

**Comment by Anton-4** [comment]
Yeah, this was all single line, so I just had to update the Roc version used by nix.

**Review by Anton-4 — APPROVED** [review]
Thanks @a-lavis!

**Pull request merged**
